[package]
name = "nucleus-rs"
version = "0.1.0"
authors = ["Thomas <thomas.bechet.pro@gmail.com>"]
edition = "2021"

[dependencies]
winit = "0.26.0"
winit_input_helper = "0.12.0"
anyhow = "1.0"
env_logger = "0.9"
log = "0.4"
futures = { version = "0.3", features = ["compat"] }
nucleus_wgpu = { path = "crates/nucleus_wgpu" }
nucleus_app = { path = "crates/nucleus_app" }