[package]
name = "mini3d_utils"
version = "0.1.0"
authors = ["Thomas <thomas.bechet.pro@gmail.com>"]
edition = "2021"

[dependencies]
mini3d = { path = "../mini3d" }
wavefront_obj = "10.0.0"
image = "0.24.3"