[package]
name = "mini3d_ffi"
version = "0.1.0"
edition = "2021"

[lib]
name = "mini3d"
crate-type = ["staticlib"]

[dependencies]
mini3d = { path = "../mini3d" }
libc="0.2.132"

[build-dependencies]
cbindgen = "0.24.3"