[package]
name = "nucleus_wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.26.0"
wgpu = "0.13.0"
bytemuck = { version = "1.10.0", features = [ "derive" ] }
rand = "0.8.5"
nucleus_renderer = { path = "../nucleus_renderer" }