[package]
name = "mini3d_winit"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.27.3"
wgpu = "0.13.1"
egui = "0.19"
egui_extras = "0.19.0"
egui_wgpu_backend = "0.19"
egui_winit_platform = "0.16"
gilrs = "0.9.0"
mini3d = { path = "../mini3d" }
mini3d_os = { path = "../mini3d_os" }
mini3d_wgpu = { path = "../mini3d_wgpu" }
mini3d_utils = { path = "../mini3d_utils" }