[package]
name = "mini3d_importer"
version = "0.1.0"
authors = ["Thomas <thomas.bechet.pro@gmail.com>"]
edition = "2021"

[dependencies]
wavefront_obj = "10.0.0"
image = "0.24.3"
mini3d_renderer = { path = "../mini3d_renderer" }
