[package]
name = "mini3d_mapper"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.64"
mini3d_input = { path = "../mini3d_input" }