[package]
name = "mini3d_os"
version = "0.1.0"
authors = ["Thomas <thomas.bechet.pro@gmail.com>"]
edition = "2021"

[dependencies]
mini3d_core = { path = "../mini3d_core" }
mini3d_derive = { path = "../mini3d_derive" }
serde = "1.0.144"
serde_json = "1.0.85"
bincode = "1.3.3"
miniz_oxide = "0.6.2"