[package]
name = "mini3d_gui"
version = "0.1.0"
authors = ["Thomas <thomas.bechet.pro@gmail.com>"]
edition = "2021"

[dependencies]
mini3d = { path = "../mini3d" }
mini3d_derive = { path = "../mini3d_derive" }