[package]
name = "mini3d_input"
version = "0.1.0"
edition = "2021"

[dependencies]
mini3d_core = { path = "../mini3d_core" }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.64"