[package]
name = "nucleus_winit"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.26.0"
wgpu = "0.13.0"
nucleus_window = { path = "../core/nucleus_window" }
nucleus_runner = { path = "../core/nucleus_runner" }