[package]
name = "mini3d_stdlog"
version = "0.1.0"
authors = ["Thomas <thomas.bechet.pro@gmail.com>"]
edition = "2021"

[dependencies]
colored = "2.0.4"
chrono = "0.4.30"
mini3d_logger = { path = "../mini3d_logger" }