[package]
name = "mini3d"
version = "0.1.0"
authors = ["Thomas <thomas.bechet.pro@gmail.com>"]
edition = "2021"

[dependencies]
mini3d_derive = { path = "../mini3d_derive" }
glam = { version = "0.21.3" }
rapier3d = "0.16.1"