[package]
name = "mini3d"
version = "0.1.0"
authors = ["Thomas <thomas.bechet.pro@gmail.com>"]
edition = "2021"

[dependencies]
glam = { version = "0.21.3", features = ["serde"] }
serde = "1.0.144"
serde_json = "1.0.91"
erased-serde = "0.3.23"
rapier3d = "0.16.1"